[features]
seeds = false
skip-lint = false

[programs.localnet]
deep_pulse = "3N5coxatEEbdLuTKovXdzrJX9E7ZAD6t2bWuz7BgGR63"

[programs.devnet]
deep_pulse = "3N5coxatEEbdLuTKovXdzrJX9E7ZAD6t2bWuz7BgGR63"

[programs.mainnet-beta]
deep_pulse = "3N5coxatEEbdLuTKovXdzrJX9E7ZAD6t2bWuz7BgGR63"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
