/**
 * DEEP Pulse Program Service
 *
 * Client SDK bridging the Anchor smart contract with the React Native frontend.
 * All on-chain interactions go through this service.
 *
 * Uses Solana Mobile Wallet Adapter (MWA) for transaction signing.
 * The $SKR token mint is: SKRbvo6Gf7GondiT3BbTfuRDPqLWei4j2Qy2NPGZhW3
 */

// MWA availability — set to true for release/custom native build
const MWA_ENABLED = true; // Enabled for Seeker release build

let transact = null;
if (MWA_ENABLED) {
  try {
    transact = require('@solana-mobile/mobile-wallet-adapter-protocol-web3js').transact;
  } catch (e) {
    logger.warn('[ProgramService] MWA import failed:', e.message);
  }
}

import {
  Connection,
  PublicKey,
  Transaction,
  SystemProgram,
} from '@solana/web3.js';
import { Program, AnchorProvider, BN, web3 } from '@coral-xyz/anchor';
import {
  TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountInstruction,
} from '@solana/spl-token';
import { Linking } from 'react-native';
import { APP_IDENTITY, getRpcEndpoint, getCluster, ADMIN_WALLET } from '../config/constants';
import { logger } from '../utils/security';

// Import IDL directly (generated by Anchor build)
import IDL from '../config/deep_pulse_idl.json';

// ============================================
// CONSTANTS
// ============================================

// Program ID (replace after deployment)
const PROGRAM_ID = new PublicKey('33vWX6efKQSZ98dk3bnbHUjEYhB7LyvbH4ndpKjC6iY4');

// $SKR Token Mint — EXISTING on Solana
const SKR_MINT = new PublicKey('SKRbvo6Gf7GondiT3BbTfuRDPqLWei4j2Qy2NPGZhW3');

// PDA Seeds
const PLATFORM_CONFIG_SEED = 'platform_config';
const TREASURY_SEED = 'treasury';
const HUB_SEED = 'hub';
const SUBSCRIPTION_SEED = 'subscription';
const DEPOSIT_SEED = 'deposit';
const ESCROW_SEED = 'escrow';
const ESCROW_AUTHORITY_SEED = 'escrow_auth'; // [C-02 FIX] Distinct seed for escrow authority PDA
const VAULT_SEED = 'vault';
const VAULT_TOKEN_SEED = 'vault_token';
const VAULT_AUTHORITY_SEED = 'vault_authority'; // [C-01 FIX] Distinct seed for vault authority PDA
const CONTRIBUTION_SEED = 'contribution';
const AD_SLOT_SEED = 'ad_slot';
const USER_SCORE_SEED = 'user_score';

const onWalletNotFound = () => {
  Linking.openURL(
    'https://play.google.com/store/search?q=solana+wallet&c=apps'
  );
};

// ============================================
// PDA DERIVATION HELPERS
// ============================================

function getPlatformConfigPda() {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(PLATFORM_CONFIG_SEED)],
    PROGRAM_ID
  );
}

function getTreasuryPda() {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(TREASURY_SEED)],
    PROGRAM_ID
  );
}

function getHubPda(creator, hubIndex) {
  const indexBuffer = Buffer.alloc(4);
  indexBuffer.writeUInt32LE(hubIndex);
  return PublicKey.findProgramAddressSync(
    [Buffer.from(HUB_SEED), creator.toBuffer(), indexBuffer],
    PROGRAM_ID
  );
}

function getSubscriptionPda(user, hubPda) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(SUBSCRIPTION_SEED), user.toBuffer(), hubPda.toBuffer()],
    PROGRAM_ID
  );
}

function getDepositPda(depositor, depositIndex) {
  const indexBuffer = Buffer.alloc(4);
  indexBuffer.writeUInt32LE(depositIndex);
  return PublicKey.findProgramAddressSync(
    [Buffer.from(DEPOSIT_SEED), depositor.toBuffer(), indexBuffer],
    PROGRAM_ID
  );
}

function getEscrowPda(depositPda) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(ESCROW_SEED), depositPda.toBuffer()],
    PROGRAM_ID
  );
}

// [C-02 FIX] Separate PDA for escrow authority (distinct from escrow token account)
function getEscrowAuthorityPda(depositPda) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(ESCROW_AUTHORITY_SEED), depositPda.toBuffer()],
    PROGRAM_ID
  );
}

function getVaultPda(hubPda, vaultIndex) {
  const indexBuffer = Buffer.alloc(4);
  indexBuffer.writeUInt32LE(vaultIndex);
  return PublicKey.findProgramAddressSync(
    [Buffer.from(VAULT_SEED), hubPda.toBuffer(), indexBuffer],
    PROGRAM_ID
  );
}

function getVaultTokenPda(vaultPda) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(VAULT_TOKEN_SEED), vaultPda.toBuffer()],
    PROGRAM_ID
  );
}

// [C-01 FIX] Separate PDA for vault authority (distinct from vault token account)
function getVaultAuthorityPda(vaultPda) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(VAULT_AUTHORITY_SEED), vaultPda.toBuffer()],
    PROGRAM_ID
  );
}

function getContributionPda(vaultPda, contributor) {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from(CONTRIBUTION_SEED),
      vaultPda.toBuffer(),
      contributor.toBuffer(),
    ],
    PROGRAM_ID
  );
}

function getAdSlotPda(hubPda, slotType, slotIndex) {
  return PublicKey.findProgramAddressSync(
    [
      Buffer.from(AD_SLOT_SEED),
      hubPda.toBuffer(),
      Buffer.from([slotType]),
      Buffer.from([slotIndex]),
    ],
    PROGRAM_ID
  );
}

function getUserScorePda(user) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(USER_SCORE_SEED), user.toBuffer()],
    PROGRAM_ID
  );
}

// ============================================
// PROGRAM SERVICE CLASS
// ============================================

class ProgramService {
  constructor() {
    this._connection = null;
    this._currentEndpoint = null;
    this._idl = null;
  }

  get connection() {
    const endpoint = getRpcEndpoint();
    if (!this._connection || this._currentEndpoint !== endpoint) {
      this._connection = new Connection(endpoint, 'confirmed');
      this._currentEndpoint = endpoint;
    }
    return this._connection;
  }

  /**
   * Get IDL — loaded from local JSON file (generated by Anchor build)
   * No need to fetch from chain, faster and works offline
   */
  getIdl() {
    if (!this._idl) {
      this._idl = IDL;
    }
    return this._idl;
  }

  // ============================================
  // HELPER: Execute transaction via MWA
  // ============================================

  async _executeMwaTransaction(buildTxFn) {
    return transact(async (wallet) => {
      const authResult = await wallet.authorize({
        chain: getCluster(),
        identity: APP_IDENTITY,
      });

      const userPubkey = new PublicKey(authResult.accounts[0].address);
      const { blockhash, lastValidBlockHeight } =
        await this.connection.getLatestBlockhash();

      const transaction = new Transaction({
        feePayer: userPubkey,
        blockhash,
        lastValidBlockHeight,
      });

      // Let caller add instructions
      await buildTxFn(transaction, userPubkey, authResult);

      // Sign and send via MWA
      const [signature] = await wallet.signAndSendTransactions({
        transactions: [transaction],
      });

      return { signature, userPubkey };
    }, { onWalletNotFound });
  }

  // ============================================
  // HELPER: Get or create ATA
  // ============================================

  async _getOrCreateAta(transaction, payer, mint, owner) {
    const ata = await getAssociatedTokenAddress(mint, owner, true);

    const accountInfo = await this.connection.getAccountInfo(ata);
    if (!accountInfo) {
      transaction.add(
        createAssociatedTokenAccountInstruction(payer, ata, owner, mint)
      );
    }

    return ata;
  }

  // ============================================
  // READ OPERATIONS (No wallet needed)
  // ============================================

  async fetchPlatformConfig() {
    const [pda] = getPlatformConfigPda();
    const idl = this.getIdl();
    if (!idl) return null;
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.platformConfig.fetch(pda);
  }

  async fetchHub(hubPda) {
    const idl = this.getIdl();
    if (!idl) return null;
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.hub.fetch(hubPda);
  }

  async fetchAllHubs() {
    const idl = this.getIdl();
    if (!idl) return [];
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.hub.all();
  }

  async fetchActiveHubs() {
    const idl = this.getIdl();
    if (!idl) return [];
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    // [H-04 FIX] Fetch all hubs and filter client-side for is_active
    // memcmp offset is fragile across Anchor versions; client-side filter is safer
    const allHubs = await program.account.hub.all();
    return allHubs.filter(h => h.account.isActive === true);
  }

  async fetchUserSubscriptions(userPubkey) {
    const idl = this.getIdl();
    if (!idl) return [];
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.hubSubscription.all([
      {
        memcmp: {
          offset: 8, // after discriminator
          bytes: userPubkey.toBase58(),
        },
      },
    ]);
  }

  async fetchUserScore(userPubkey) {
    const [pda] = getUserScorePda(userPubkey);
    const idl = this.getIdl();
    if (!idl) return null;
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    try {
      return await program.account.userScore.fetch(pda);
    } catch {
      return null; // Score not initialized yet
    }
  }

  async fetchDaoVault(vaultPda) {
    const idl = this.getIdl();
    if (!idl) return null;
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.daoVault.fetch(vaultPda);
  }

  async fetchOpenVaultsForHub(hubPda) {
    const idl = this.getIdl();
    if (!idl) return [];
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.daoVault.all([
      {
        memcmp: {
          offset: 8 + 32, // after discriminator + proposal_deposit
          bytes: hubPda.toBase58(),
        },
      },
    ]);
  }

  async fetchActiveAdsForHub(hubPda) {
    const idl = this.getIdl();
    if (!idl) return [];
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.adSlot.all([
      {
        memcmp: {
          offset: 8 + 32, // after discriminator + advertiser
          bytes: hubPda.toBase58(),
        },
      },
    ]);
  }

  async fetchPendingDepositsForHub(hubPda) {
    const idl = this.getIdl();
    if (!idl) return [];
    const program = new Program(idl, PROGRAM_ID, { connection: this.connection });
    return program.account.deposit.all([
      {
        memcmp: {
          offset: 8 + 32, // after discriminator + depositor = hub field
          bytes: hubPda.toBase58(),
        },
      },
    ]);
  }

  // ============================================
  // WRITE OPERATIONS (MWA transaction signing)
  // ============================================

  /**
   * Initialize user score (call once per user, before scoring works)
   */
  async initUserScore() {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [userScorePda] = getUserScorePda(userPubkey);
      const [platformConfigPda] = getPlatformConfigPda();

      // Build instruction manually (without full Anchor program on mobile)
      // In practice, you'd use the IDL to build this instruction
      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .initUserScore()
        .accounts({
          user: userPubkey,
          userScore: userScorePda,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Create a new hub (brand pays $SKR subscription)
   */
  async createHub(name, description, category, hubIndex) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [hubPda] = getHubPda(userPubkey, hubIndex);
      const [platformConfigPda] = getPlatformConfigPda();
      const [treasuryPda] = getTreasuryPda();

      const creatorAta = await getAssociatedTokenAddress(SKR_MINT, userPubkey);
      const treasuryAta = await getAssociatedTokenAddress(
        SKR_MINT,
        treasuryPda,
        true
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .createHub(name, description, { [category]: {} }, hubIndex)
        .accounts({
          creator: userPubkey,
          hub: hubPda,
          platformConfig: platformConfigPda,
          creatorTokenAccount: creatorAta,
          treasuryTokenAccount: treasuryAta,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Subscribe to a hub (free in $SKR, rent only)
   */
  async subscribeToHub(hubPda) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [subscriptionPda] = getSubscriptionPda(userPubkey, hubPda);
      const [userScorePda] = getUserScorePda(userPubkey);

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      // Check if user score account exists (getAccountInfo returns null, doesn't throw)
      let userScore = null;
      const userScoreInfo = await this.connection.getAccountInfo(userScorePda);
      if (userScoreInfo) {
        userScore = userScorePda;
      }

      const ix = await program.methods
        .subscribeToHub()
        .accounts({
          user: userPubkey,
          hub: hubPda,
          subscription: subscriptionPda,
          userScore: userScore,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Unsubscribe from a hub (rent returned)
   */
  async unsubscribeFromHub(hubPda) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [subscriptionPda] = getSubscriptionPda(userPubkey, hubPda);

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .unsubscribeFromHub()
        .accounts({
          user: userPubkey,
          hub: hubPda,
          subscription: subscriptionPda,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Create a deposit (feedback/talent/dao_proposal)
   * depositType: 'feedback' | 'daoProposal' | 'talent'
   */
  async createDeposit(hubPda, depositType, contentHash, depositIndex) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [depositPda] = getDepositPda(userPubkey, depositIndex);
      const [escrowPda] = getEscrowPda(depositPda);
      const [escrowAuthorityPda] = getEscrowAuthorityPda(depositPda); // [C-02 FIX]
      const [platformConfigPda] = getPlatformConfigPda();
      const [userScorePda] = getUserScorePda(userPubkey);

      const depositorAta = await getAssociatedTokenAddress(
        SKR_MINT,
        userPubkey
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      // Map string type to enum
      const typeEnum = { [depositType]: {} };

      // Check if user score account exists (getAccountInfo returns null, doesn't throw)
      let userScore = null;
      const userScoreInfo = await this.connection.getAccountInfo(userScorePda);
      if (userScoreInfo) {
        userScore = userScorePda;
      }

      const ix = await program.methods
        .createDeposit(typeEnum, contentHash, depositIndex)
        .accounts({
          depositor: userPubkey,
          hub: hubPda,
          deposit: depositPda,
          escrowTokenAccount: escrowPda,
          escrowAuthority: escrowAuthorityPda, // [C-02 FIX] Distinct PDA
          platformConfig: platformConfigPda,
          depositorTokenAccount: depositorAta,
          skrMint: SKR_MINT,
          userScore: userScore,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: web3.SYSVAR_RENT_PUBKEY,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Approve feedback (brand moderates — refund to user)
   */
  async approveFeedback(depositPda, hubPda, depositorPubkey) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [escrowPda] = getEscrowPda(depositPda);
      const [escrowAuthorityPda] = getEscrowAuthorityPda(depositPda); // [C-02 FIX]
      const depositorAta = await getAssociatedTokenAddress(
        SKR_MINT,
        depositorPubkey
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .approveFeedback()
        .accounts({
          resolver: userPubkey,
          deposit: depositPda,
          hub: hubPda,
          escrowTokenAccount: escrowPda,
          escrowAuthority: escrowAuthorityPda, // [C-02 FIX] Distinct PDA
          depositorTokenAccount: depositorAta,
          depositor: depositorPubkey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Approve talent submission (brand moderates — refund to user)
   */
  async approveTalent(depositPda, hubPda, depositorPubkey) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [escrowPda] = getEscrowPda(depositPda);
      const [escrowAuthorityPda] = getEscrowAuthorityPda(depositPda); // [C-02 FIX]
      const depositorAta = await getAssociatedTokenAddress(
        SKR_MINT,
        depositorPubkey
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .approveTalent()
        .accounts({
          resolver: userPubkey,
          deposit: depositPda,
          hub: hubPda,
          escrowTokenAccount: escrowPda,
          escrowAuthority: escrowAuthorityPda, // [C-02 FIX] Distinct PDA
          depositorTokenAccount: depositorAta,
          depositor: depositorPubkey,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Reject a deposit (tokens go to treasury)
   */
  async rejectDeposit(depositPda, hubPda, depositorPubkey) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [escrowPda] = getEscrowPda(depositPda);
      const [escrowAuthorityPda] = getEscrowAuthorityPda(depositPda); // [C-02 FIX]
      const [platformConfigPda] = getPlatformConfigPda();
      const [treasuryPda] = getTreasuryPda();
      const treasuryAta = await getAssociatedTokenAddress(
        SKR_MINT,
        treasuryPda,
        true
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .rejectDeposit()
        .accounts({
          resolver: userPubkey,
          deposit: depositPda,
          hub: hubPda,
          escrowTokenAccount: escrowPda,
          escrowAuthority: escrowAuthorityPda, // [C-02 FIX] Distinct PDA
          treasuryTokenAccount: treasuryAta,
          depositor: depositorPubkey,
          platformConfig: platformConfigPda,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Approve DAO proposal (refund + create vault)
   */
  async approveDaoProposal(
    depositPda,
    hubPda,
    depositorPubkey,
    vaultIndex,
    title,
    description,
    targetAmount,
    expiresAt
  ) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [escrowPda] = getEscrowPda(depositPda);
      const [escrowAuthorityPda] = getEscrowAuthorityPda(depositPda); // [C-02 FIX]
      const [vaultPda] = getVaultPda(hubPda, vaultIndex);
      const [vaultTokenPda] = getVaultTokenPda(vaultPda);
      const [vaultAuthorityPda] = getVaultAuthorityPda(vaultPda); // [C-01 FIX]
      const [platformConfigPda] = getPlatformConfigPda();

      const depositorAta = await getAssociatedTokenAddress(
        SKR_MINT,
        depositorPubkey
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .approveDaoProposal(
          vaultIndex,
          title,
          description,
          new BN(targetAmount),
          new BN(expiresAt)
        )
        .accounts({
          resolver: userPubkey,
          deposit: depositPda,
          hub: hubPda,
          escrowTokenAccount: escrowPda,
          escrowAuthority: escrowAuthorityPda, // [C-02 FIX] Distinct PDA
          depositorTokenAccount: depositorAta,
          depositor: depositorPubkey,
          daoVault: vaultPda,
          vaultTokenAccount: vaultTokenPda,
          vaultTokenAuthority: vaultAuthorityPda, // [C-01 FIX] Distinct PDA
          platformConfig: platformConfigPda,
          skrMint: SKR_MINT,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          rent: web3.SYSVAR_RENT_PUBKEY,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Contribute to a DAO vault
   */
  async contributeToVault(vaultPda, amount) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [vaultTokenPda] = getVaultTokenPda(vaultPda);
      const [contributionPda] = getContributionPda(vaultPda, userPubkey);
      const [platformConfigPda] = getPlatformConfigPda();
      const [userScorePda] = getUserScorePda(userPubkey);

      const contributorAta = await getAssociatedTokenAddress(
        SKR_MINT,
        userPubkey
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      // Check if user score account exists (getAccountInfo returns null, doesn't throw)
      let userScore = null;
      const userScoreInfo = await this.connection.getAccountInfo(userScorePda);
      if (userScoreInfo) {
        userScore = userScorePda;
      }

      const ix = await program.methods
        .contributeToVault(new BN(amount))
        .accounts({
          contributor: userPubkey,
          daoVault: vaultPda,
          contribution: contributionPda,
          vaultTokenAccount: vaultTokenPda,
          contributorTokenAccount: contributorAta,
          platformConfig: platformConfigPda,
          userScore: userScore,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      tx.add(ix);
    });
  }

  /**
   * Purchase an ad slot
   */
  async purchaseAdSlot(
    hubPda,
    slotType,
    slotIndex,
    imageUrlHash,
    landingUrlHash,
    durationWeeks
  ) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      // [H-06 FIX] Support all three slot types (top, bottom, lockscreen)
      const slotTypeMap = { top: 0, bottom: 1, lockscreen: 2 };
      const slotTypeNum = slotTypeMap[slotType] ?? 1;
      const [adSlotPda] = getAdSlotPda(hubPda, slotTypeNum, slotIndex);
      const [platformConfigPda] = getPlatformConfigPda();
      const [treasuryPda] = getTreasuryPda();

      const advertiserAta = await getAssociatedTokenAddress(
        SKR_MINT,
        userPubkey
      );
      const treasuryAta = await getAssociatedTokenAddress(
        SKR_MINT,
        treasuryPda,
        true
      );

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const typeEnumMap = { top: { top: {} }, bottom: { bottom: {} }, lockscreen: { lockscreen: {} } };
      const typeEnum = typeEnumMap[slotType] || { bottom: {} };

      const ix = await program.methods
        .purchaseAdSlot(
          typeEnum,
          slotIndex,
          imageUrlHash,
          landingUrlHash,
          durationWeeks
        )
        .accounts({
          advertiser: userPubkey,
          hub: hubPda,
          adSlot: adSlotPda,
          platformConfig: platformConfigPda,
          advertiserTokenAccount: advertiserAta,
          treasuryTokenAccount: treasuryAta,
          tokenProgram: TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
        })
        .instruction();

      tx.add(ix);
    });
  }

  // ============================================
  // UTILITY: Content hash helper
  // ============================================

  /**
   * Create a SHA-256 hash for content (feedback text, proposal, etc.)
   * Used as content_hash parameter for deposits
   */
  async hashContent(content) {
    // React Native compatible SHA-256 using js-sha256 (no crypto.subtle)
    // [H-02 FIX] Improved fallback — multi-round mixing instead of weak XOR
    try {
      const { sha256 } = require('js-sha256');
      const hash = sha256.array(content);
      return hash.slice(0, 32);
    } catch (error) {
      // Fallback: multi-round mixing hash (js-sha256 should always be available)
      console.error('[ProgramService] js-sha256 not available, using fallback hash');
      const data = Buffer.from(content, 'utf-8');
      const hash = new Uint8Array(32);
      hash[0] = data.length & 0xff;
      hash[1] = (data.length >> 8) & 0xff;
      for (let round = 0; round < 4; round++) {
        for (let i = 0; i < data.length; i++) {
          const idx = (i + round * 7) % 32;
          hash[idx] = (hash[idx] * 31 + data[i] + round * 17 + i) & 0xff;
          hash[(idx + 13) % 32] ^= hash[idx] ^ data[i];
          hash[(idx + 7) % 32] = (hash[(idx + 7) % 32] + hash[idx]) & 0xff;
        }
      }
      return Array.from(hash);
    }
  }

  /**
   * Update platform config prices (admin only)
   * Only sends non-null values — on-chain instruction uses Option<T>
   */
  async updatePlatformConfig(priceUpdates) {
    return this._executeMwaTransaction(async (tx, userPubkey) => {
      const [platformConfigPda] = getPlatformConfigPda();

      const idl = this.getIdl();
      const program = new Program(idl, PROGRAM_ID, {
        connection: this.connection,
      });

      const ix = await program.methods
        .updatePlatformConfig(
          priceUpdates.hubSubscriptionPrice ?? null,
          priceUpdates.feedbackDeposit ?? null,
          priceUpdates.daoProposalDeposit ?? null,
          priceUpdates.talentDeposit ?? null,
          priceUpdates.topAdPricePerWeek ?? null,
          priceUpdates.bottomAdPricePerWeek ?? null,
          priceUpdates.daoBrandShareBps ?? null,
          priceUpdates.daoPlatformShareBps ?? null,
          priceUpdates.minVaultContribution ?? null,
        )
        .accounts({
          admin: userPubkey,
          platformConfig: platformConfigPda,
        })
        .instruction();

      tx.add(ix);
    });
  }
}

// Export singleton
export const programService = new ProgramService();

// Export PDA helpers for direct use
export {
  PROGRAM_ID,
  SKR_MINT,
  getPlatformConfigPda,
  getTreasuryPda,
  getHubPda,
  getSubscriptionPda,
  getDepositPda,
  getEscrowPda,
  getEscrowAuthorityPda,
  getVaultPda,
  getVaultTokenPda,
  getVaultAuthorityPda,
  getContributionPda,
  getAdSlotPda,
  getUserScorePda,
};
